### ISSUE TITLE
关于清除浮动

### ISSUE THREAD

**Issue by bencode** [qingguatang/fe-homework#13]
From: [uemuki](https://github.com/uemuki)

有些网页上清除浮动使用`.clearfix:after {}`中会比课上的多几个属性“height: 0;”、“inline-height: 0;”、“visibility: hidden;”，既然content、display、clear已经够用了，为什么要写这些写属性？有些还需要再写上`.clearfix {zoom: 1;}`来解决兼容性问题，在好多地方看到过`zoom: 1;`这个属性-值，那么它的本质意义是什么呢， 在什么情况下可以使用它呢？

**Comment by bencode** [comment]
浮动元素默认不占文档流，浮动用于布局时，往往需要将容器撑开，这就需要在容器中添加额外的节点，并设置CSS `clear`属性。 这个额外的元素一般使用 `:after` 伪类或 `::after` 伪元素生成，以避免书写额外的HTML标签。

在主流浏览器中，以下代码足够了：

```css
.clearfix::after {
  display: block;
  content: '';
  clear: both；
}
```

但是 `::after` 伪元素在 **IE8** 中不支持， 所以要支持 IE8，可使用 `:after` 伪类：

```css
.clearfix:after {
   ...
}
```

但是你可能看到一些古老的代码，需要支持 **IE7及更早的IE浏览器**， 它们连 `:after` 伪类也是不支持的，所以要做特别的处理。 

[after伪元素支持情况](https://caniuse.com/#search=%3Aafter) 

而IE7及更高版本要让容器闭合浮动元素，另有一套逻辑，叫**hasLayout**， 你可以随便google一下就能看到一些资料， 不看也无所谓，总结起来，就是可以设置一些css属性，让元素具有`hasLayout`特性， 它就会自动闭合浮动元素。 那你上面提到的的`height`，`zoom:1` 都是此流。而`zoom:1` 是其中最没副作用的，所以常用来支持IE7及更早版本的清除浮动。

所以你查看代码时会看到很多这样的写法。

```css
.clearfix {
  zoom: 1; 
}
.clearfix:after {
  display: block;
  content: '';
  clear: both;
}
```

现在这样的代码基础上用不到了， 不过可能你去面试时偶尔会碰到，我估计以后面试这样的问题也不会问了。。

此外，在以前IE的时代，会针对不同版本写不同样式的`hack`，也可以google了解下。
